### PR TITLE
Fix CORS Errors

### LINKED ISSUE #43: Fix CORS errors
Requests from frontend to API gateway fail due to CORS errors

https://stackoverflow.com/questions/64281334/cors-errors-when-trying-to-fetch-from-new-google-cloud-api-gateway

Approach is to:
1. Add `options` preflight to each request in the OpenAPI config.
2. For each backend service add middleware that handles the `options` preflight requests and returns the proper CORS headers: 
Like in here: [https://cloud.google.com/functions/docs/writing/write-http-functions#authentication_and_cors](url) 
Or like in: [https://stackoverflow.com/questions/33483675/getting-express-server-to-accept-cors-request](url)

I pray that this will work

### PR DESCRIPTION
**Pull request by toastjpg**
TODO: Need to add the middle ware within the actual backend services to handle the `options` preflight requests

Deploying the updated OpenAPI config file seems to work, but the fetch requests are still giving CORS errors....

### CODE REVIEW

**Review by jerrydngzh — APPROVED** [review]
lfg

**Comment by toastjpg** [comment]
dont get excited this shit doesnt work

im making the PR and linking to an issue with relevant resources in hopes one of you can figure it out 

i need food

**Review by jerrydngzh — APPROVED** [review]
lgtm

**Comment by jerrydngzh** [comment]
lfg (for real)

**Pull request merged**
