### PR TITLE
format response jsons

### PR DESCRIPTION
**Pull request by toastjpg**
nitpick but i formatted all the responses to be actual objects instead of strings

### CODE REVIEW

**Comment by risakawagoe** [comment]
I see you changed the response format. That seems fine but just wondering if you updated the front end? Did you check if the Frontend  accesses the response data appropriately?
E.g) if response format changed to {message: "error: blubluh"}

Old version:
Catch(error) {
Const data = await response.json()
Alert(data)
}

New version:
Catch(error) {
Const data = await response.json()
Alert(data.message) // needs to be changed
}

**Comment by toastjpg** [comment]
oh thanks for reminder i will make those changes in the frontend then. 

Are all the usages found through the controller files?

**Comment by risakawagoe** [comment]
> Are all the usages found through the controller files?

yes i believe so

**Comment by toastjpg** [comment]
@risakawagoe edited all references to response object in frontend for quiz and media service

**Review by jerrydngzh — APPROVED** [review]
lgtm, changes are small and easy to review 👍

**Pull request merged**
