### PR TITLE
migrate user services to profile service and use Firestore

### LINKED ISSUE #21: migrating auth + user service off postgres to firestore
Working off of Firestore connection logic from #18 and #20.

Will keep Auth Service endpoints and functionality the same to be integrated during account signup workflow for user email verification.

User Service will be converted to Profile Service and store user profile related data (bio, about me, etc?). Since user accounts and login will be managed by Firebase Auth from Jerry's auth integration work.

### PR DESCRIPTION
**Pull request by toastjpg**
Profile service currently just two endpoints and are stubbed. Intended to store strings associated with profile data. GET and PUT endpoints only. 

TODO: Need to figure out how to actually write the firestore controller functions and where to put them lol

Seems like the quiz service doesn't use the controller file? Not sure if the way it connects to Firestore instance works.

### CODE REVIEW

**Comment by Toastjpg** [comment]
test

**Comment by toastjpg** [comment]
Migrated auth and profile services to service folder and added endpoints for profile service.

Profile service endpoints are:

`GET /api/profile/:id`

- Returns document fields as a JSON object

`PUT /api/profile/`

Body:
```javascript
{
  id: someUniqueUserID,
  content: {
    fields: "a json object containing the fields for the document to be created/overwritten"
  }
}
``` 
- Returns message with id of the document created/modified

**Comment by toastjpg** [comment]
Auth service firestore migration in #27

**Review by yenuGH — APPROVED** [review]
assuming the profile service is to be left non functional (creating a profile in itself, which is what i remember we said we would leave it as), looks good to me

**Comment by toastjpg** [comment]
Yeah so its not connected to frontend anywhere really right now, its just so we can have the service around. I can build off the profile component that risa made in the frontend later to support a user changing their display name + bio or something

**Pull request merged**
